backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
# This line should *not* be indented
local_backend: true # Whether to use the local backend (optional; defaults to false)
publish_mode: editorial_workflow
logo_url: https://activecollective-netlify.netlify.app/assets/img/logos/active-collective_logo_white.svg
# This line should *not* be indented
media_folder: "assets/img/uploads" # Media files will be stored in the repo under assets/images/uploads
public_folder: "/assets/img/uploads" # Media files will be served from /assets/images/uploads
collections:
  - label: "Contact Page"
    name: "contact"
    preview_path: "https://activecollective-netlify.netlify.app/contact/"
    files:
      - label: "Info"
        name: "info"
        file: "src/_data/pages/contact/info.json"
        fields:
          - label: "Address"
            name: "address"
            widget: "object"
            fields:
              - {label: Title, name: "heading", widget: string}
              - {label: Address, name: "data", widget: string}
          - label: "Telephone"
            name: "telephone"
            widget: "object"
            fields:
              - {label: Title, name: "heading", widget: string}
              - {label: Telephone number, name: "data", widget: string}
          - label: "Email"
            name: "email"
            widget: "object"
            fields:
              - {label: Title, name: "heading", widget: string}
              - {label: E-mail, name: "data", widget: string}
          - label: "Jobs"
            name: "jobs"
            widget: "object"
            fields:
              - {label: Title, name: "heading", widget: string}
              - {label: E-mail, name: "data", widget: string}
          - label: "Legal"
            name: "legal"
            widget: "object"
            fields:
              - {label: Title, name: "heading", widget: string}
              - label: Data
                name: "data"
                widget: "object"
                fields:
                - {label: KvK, name: "kvk", widget: number}
                - {label: BTW, name: "btw", widget: string}
      - label: "Socials"
        name: "socials"
        file: "src/_data/pages/contact/socials.json"
        widget: 'list'
        fields:
          - {label: Title, name: "title", widget: "hidden"}
          - {label: Instagram URL, name: instagram, widget: string}
          - {label: Facebook URL, name: facebook, widget: string}
          - {label: LinkedIN URL, name: linkedin, widget: string}
          - {label: Twitter URL, name: twitter, widget: string}
          - {label: Youtube URL, name: youtube, widget: string}          
  - label: "About Page"
    name: "about"
    preview_path: "https://activecollective-netlify.netlify.app/about/"
    files:
      - label: "Manifesto list"
        name: "list"
        file: "src/_data/pages/about/manifesto.json"
        fields:
          - label: "Manifesto"
            name: "list"
            widget: "list"
            create: true
            collapsed: false
            fields:
              - {label: ID, name: "id", widget: "hidden"}
              - {label: Title, name: "title", widget: string}
              - {label: Description, name: "description", widget: string}
  - label: "Posts"
    name: posts
    folder: "src/posts"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Paginatitel", name: "title", widget: "string" }
      - { label: "Auteur", name: "auteur", widget: "string" }
      - { label: "Leestijd in minuten", name: "minutesRead", widget: "number" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Content blocks"
        name: "content"
        widget: "list"
        collapsed: false
        fields:
          - label: "Content blocks"
            name: "contentBlock" # this is [0], [1] or [2]
            widget: "list"
            collapsed: false
            create: true
            fields:
              - {label: "Paragraph", name: "text", widget: "markdown"} 
              - {label: "Heading", name: "heading", widget: "hidden"}
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["nieuws", "posts", "studiereizen"]